window.MAXIE_ANIMATIONS = {
  idle: { label: "Idle", energyCost: 0 },
  walk: { label: "Walk", energyCost: 1 },
  run: { label: "Run", energyCost: 3 },
  jump: { label: "Jump", energyCost: 2 },
  sit: { label: "Sit", energyCost: 0 },
  sleep: { label: "Sleep", energyCost: -4 },
  yawn: { label: "Yawn", energyCost: 0 },
  eat: { label: "Eat", energyCost: -2 },
  hungry: { label: "Hungry", energyCost: 0 },
  drink: { label: "Drink", energyCost: -1 },
  full: { label: "Full", energyCost: -1 },
  wave: { label: "Wave", energyCost: 1 },
  dance: { label: "Dance", energyCost: 3 },
  cry: { label: "Cry", energyCost: 1 },
  laugh: { label: "Laugh", energyCost: 1 },
  sing: { label: "Sing", energyCost: 2 },
  happy: { label: "Happy", energyCost: 1 },
  angry: { label: "Angry", energyCost: 1 },
  surprised: { label: "Surprised", energyCost: 1 },
  watching: { label: "Watching", energyCost: 0 },
  focused: { label: "Focused", energyCost: 1 },
  gaming: { label: "Gaming", energyCost: 2 },
  win: { label: "Win", energyCost: 2 },
  lose: { label: "Lose", energyCost: 1 },
  notification: { label: "Notification", energyCost: 1 },
  message: { label: "Message", energyCost: 0 },
  headphones: { label: "Headphones", energyCost: 0 },
  idea: { label: "Idea", energyCost: 0 },
  writing: { label: "Writing", energyCost: 1 },
  plan: { label: "Plan", energyCost: 0 },
  highfive: { label: "High five", energyCost: 1 },
  attention: { label: "Attention", energyCost: 1 },
  sunny: { label: "Sunny", energyCost: 0 },
  rainy: { label: "Rainy", energyCost: 0 },
  cold: { label: "Cold", energyCost: 1 },
  cloudy: { label: "Cloudy", energyCost: 0 },
  popcorn: { label: "Popcorn", energyCost: 1 },
  thumbsup: { label: "Thumbs up", energyCost: 1 },
  error: { label: "Error", energyCost: 1 },
  success: { label: "Success", energyCost: 2 },
  rubberduck: { label: "Rubber duck", energyCost: 0 },
  controller: { label: "Controller", energyCost: 1 },
  duck: { label: "Duck mode", energyCost: 1 },
  clean: { label: "Cleaning", energyCost: 1 },
  mousechase: { label: "Mouse chase", energyCost: 2 },
  butterfly: { label: "Butterfly", energyCost: 1 },
  upsidedown: { label: "Upside-down sleep", energyCost: 0 },
  rocket: { label: "Rocket", energyCost: 3 },
  ghost: { label: "Ghost", energyCost: 0 },
  gift: { label: "Gift", energyCost: 0 },
  hat: { label: "Hat", energyCost: 0 },
  balloon: { label: "Balloon", energyCost: 0 },
  toy: { label: "Toy", energyCost: 0 },
  hug: { label: "Hug", energyCost: 1 },
  bed: { label: "Bed", energyCost: 0 },
  snore: { label: "Snore", energyCost: -2 },
  climb: { label: "Climb", energyCost: 2 },
  grab: { label: "Grab", energyCost: 1 },
  hang: { label: "Hang", energyCost: 1 },
  edgewalk: { label: "Edge walk", energyCost: 1 },
  windowedge: { label: "Window edge", energyCost: 1 },
  ceilingwalk: { label: "Ceiling walk", energyCost: 2 },
  wallwalk: { label: "Wall walk", energyCost: 2 },
  leap: { label: "Leap", energyCost: 3 },
  land: { label: "Land", energyCost: 1 },
  slip: { label: "Slip", energyCost: 1 },
  recover: { label: "Recover", energyCost: 1 },
  sitwindow: { label: "Sit on window", energyCost: 0 },
  explore: { label: "Explore", energyCost: 1 },
  laptop: { label: "Laptop", energyCost: 1 },
  battery: { label: "Battery", energyCost: 0 },
  worry: { label: "Worried", energyCost: 1 },
  coffee: { label: "Coffee", energyCost: -1 },
  football: { label: "Football", energyCost: 2 },
  yoyo: { label: "Yo-yo", energyCost: 1 },
  kite: { label: "Kite", energyCost: 1 },
  bone: { label: "Bone", energyCost: 1 },
  teddy: { label: "Teddy", energyCost: 0 },
  book: { label: "Book", energyCost: 0 },
  phone: { label: "Phone", energyCost: 0 },
  guitar: { label: "Guitar", energyCost: 2 },
  switch: { label: "Switch", energyCost: 2 },
  umbrella: { label: "Umbrella", energyCost: 0 },
  wind: { label: "Wind", energyCost: 2 },
  snowman: { label: "Snowman", energyCost: 0 },
  icecream: { label: "Ice cream", energyCost: -1 },
  blanket: { label: "Blanket", energyCost: 0 },
  blushhappy: { label: "Blush happy", energyCost: 0 },
  love: { label: "Love", energyCost: 0 },
  shy: { label: "Shy", energyCost: 0 },
  dizzy: { label: "Dizzy", energyCost: 1 },
  sparklehappy: { label: "Sparkle happy", energyCost: 1 },
  mirror: { label: "Mirror", energyCost: 0 },
  bubbles: { label: "Bubbles", energyCost: 1 },
  selfie: { label: "Selfie", energyCost: 1 },
  pizza: { label: "Pizza", energyCost: -1 },
  cake: { label: "Cake", energyCost: -1 },
  costume: { label: "Costume", energyCost: 0 },
  package: { label: "Package", energyCost: 0 },
  raincoat: { label: "Raincoat", energyCost: 0 },
  mask: { label: "Mask", energyCost: 0 },
  juice: { label: "Juice", energyCost: -1 },
  ufo: { label: "UFO", energyCost: 1 },
  dragon: { label: "Dragon", energyCost: 2 },
  meteor: { label: "Meteor", energyCost: 2 },
  rainbow: { label: "Rainbow", energyCost: 0 },
  treasure: { label: "Treasure", energyCost: 0 },
  robot: { label: "Robot", energyCost: 0 },
  fireworks: { label: "Fireworks", energyCost: 1 },
  adventure: { label: "Adventure", energyCost: 2 },
  family: { label: "Family", energyCost: 0 },
  evolve: { label: "Evolve", energyCost: 2 },
  story: { label: "Story", energyCost: 0 },
  listen: { label: "Listen", energyCost: 0 },
  thinking: { label: "Thinking", energyCost: 0 },
  typing: { label: "Typing", energyCost: 1 },
  celebrate: { label: "Celebrate", energyCost: 2 },
  fall: { label: "Fall over", energyCost: 2 },
  stretch: { label: "Stretch", energyCost: 0 }
};
